package passes

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/ratoru/hledger-build/internal/config"
	"github.com/ratoru/hledger-build/internal/runner"
)

// WriteImportStubs generates sources/{year}-imports.journal for each year in
// [cfg.FirstYear, cfg.CurrentYear]. Each stub lists include directives for all
// Pass 1 ingest-journal outputs for that year, so users only need a single
// line in their {year}.journal:
//
//	include sources/{year}-imports.journal
//
// Include paths are written relative to the sources/ directory so that
// hledger resolves them correctly. Stubs are written atomically and only
// when their content changes, so unchanged builds do not alter file timestamps.
func WriteImportStubs(cfg *config.Config, pass1Steps []runner.Step) error {
	if cfg.FirstYear == 0 || cfg.CurrentYear == 0 {
		return nil
	}

	sourcesPrefix := cfg.Directories.Sources + "/"

	// Group ingest journal outputs by year.
	// Paths are project-root-relative; strip the leading "sources/" so that
	// each include resolves correctly relative to the stub's own location.
	byYear := make(map[int][]string)
	for _, step := range pass1Steps {
		if !step.IsIngestJournal {
			continue
		}
		year := journalYearFromPath(step.Output)
		if year == 0 {
			continue
		}
		rel := strings.TrimPrefix(step.Output, sourcesPrefix)
		byYear[year] = append(byYear[year], rel)
	}

	sourcesDir := filepath.Join(cfg.ProjectRoot, cfg.Directories.Sources)
	if err := os.MkdirAll(sourcesDir, 0o755); err != nil {
		return fmt.Errorf("creating sources dir: %w", err)
	}

	for year := cfg.FirstYear; year <= cfg.CurrentYear; year++ {
		outputs := byYear[year]
		sort.Strings(outputs)

		var buf strings.Builder
		buf.WriteString("; Auto-generated by hledger-build. Do not edit.\n")
		for _, o := range outputs {
			buf.WriteString("include ")
			buf.WriteString(o)
			buf.WriteString("\n")
		}

		stubPath := filepath.Join(sourcesDir, strconv.Itoa(year)+"-imports.journal")
		if err := writeStubIfChanged(stubPath, []byte(buf.String())); err != nil {
			return fmt.Errorf("writing import stub for %d: %w", year, err)
		}
	}
	return nil
}

// journalYearFromPath extracts the year from a path like
// "sources/bank/checking/journal/2026/txns.journal" by treating the
// second-to-last path component as the year.
func journalYearFromPath(path string) int {
	parts := strings.Split(path, "/")
	if len(parts) < 2 {
		return 0
	}
	y, err := strconv.Atoi(parts[len(parts)-2])
	if err != nil || y < 1900 || y > 2100 {
		return 0
	}
	return y
}

// writeStubIfChanged writes data to path only when the existing content
// differs. Uses an atomic temp-file + rename to avoid partial writes.
func writeStubIfChanged(path string, data []byte) error {
	existing, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("reading %q: %w", path, err)
	}
	if bytes.Equal(existing, data) {
		return nil
	}

	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".hledger-build-stub-*")
	if err != nil {
		return fmt.Errorf("creating temp file: %w", err)
	}
	tmpName := tmp.Name()
	defer func() { _ = os.Remove(tmpName) }()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return fmt.Errorf("writing temp file: %w", err)
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("closing temp file: %w", err)
	}
	return os.Rename(tmpName, path)
}
