package passes

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/ratoru/hledger-build/internal/config"
	"github.com/ratoru/hledger-build/internal/runner"
)

func TestJournalYearFromPath(t *testing.T) {
	cases := []struct {
		path string
		want int
	}{
		{"sources/mybank/checking/journal/2026/txns.journal", 2026},
		{"sources/amex/credit/journal/2025/statements.journal", 2025},
		{"sources/bank/journal/1999/old.journal", 1999},
		{"sources/bank/journal/notayear/file.journal", 0},
		{"tooshort.journal", 0},
		{"reports/2026-all.journal", 0}, // "reports" is not a year
	}
	for _, c := range cases {
		got := journalYearFromPath(c.path)
		if got != c.want {
			t.Errorf("journalYearFromPath(%q) = %d, want %d", c.path, got, c.want)
		}
	}
}

func TestWriteImportStubs_Basic(t *testing.T) {
	dir := t.TempDir()
	cfg := &config.Config{
		ProjectRoot: dir,
		FirstYear:   2025,
		CurrentYear: 2026,
		Directories: config.Directories{Sources: "sources"},
	}

	steps := []runner.Step{
		{Output: "sources/bank/checking/journal/2026/txns.journal", IsIngestJournal: true, Pass: 1},
		{Output: "sources/amex/credit/journal/2026/stmts.journal", IsIngestJournal: true, Pass: 1},
		{Output: "sources/bank/checking/journal/2025/txns.journal", IsIngestJournal: true, Pass: 1},
		// Non-journal step: should be ignored.
		{Output: "sources/bank/checking/cleaned/2026/txns.csv", IsIngestJournal: false, Pass: 1},
	}

	if err := WriteImportStubs(cfg, steps); err != nil {
		t.Fatal(err)
	}

	// Check 2026 stub — paths relative to sources/.
	stub2026, err := os.ReadFile(filepath.Join(dir, "sources", "2026-imports.journal"))
	if err != nil {
		t.Fatal(err)
	}
	want2026 := "; Auto-generated by hledger-build. Do not edit.\n" +
		"include amex/credit/journal/2026/stmts.journal\n" +
		"include bank/checking/journal/2026/txns.journal\n"
	if string(stub2026) != want2026 {
		t.Errorf("2026 stub:\ngot:  %q\nwant: %q", string(stub2026), want2026)
	}

	// Check 2025 stub.
	stub2025, err := os.ReadFile(filepath.Join(dir, "sources", "2025-imports.journal"))
	if err != nil {
		t.Fatal(err)
	}
	want2025 := "; Auto-generated by hledger-build. Do not edit.\n" +
		"include bank/checking/journal/2025/txns.journal\n"
	if string(stub2025) != want2025 {
		t.Errorf("2025 stub:\ngot:  %q\nwant: %q", string(stub2025), want2025)
	}
}

func TestWriteImportStubs_EmptyYear(t *testing.T) {
	dir := t.TempDir()
	cfg := &config.Config{
		ProjectRoot: dir,
		FirstYear:   2026,
		CurrentYear: 2026,
		Directories: config.Directories{Sources: "sources"},
	}

	// No steps — stub should still be written, just with header only.
	if err := WriteImportStubs(cfg, nil); err != nil {
		t.Fatal(err)
	}

	stub, err := os.ReadFile(filepath.Join(dir, "sources", "2026-imports.journal"))
	if err != nil {
		t.Fatal(err)
	}
	want := "; Auto-generated by hledger-build. Do not edit.\n"
	if string(stub) != want {
		t.Errorf("got %q, want %q", string(stub), want)
	}
}

func TestWriteImportStubs_NoYears(t *testing.T) {
	dir := t.TempDir()
	cfg := &config.Config{
		ProjectRoot: dir,
		FirstYear:   0,
		CurrentYear: 0,
		Directories: config.Directories{Sources: "sources"},
	}
	// Should be a no-op without error.
	if err := WriteImportStubs(cfg, nil); err != nil {
		t.Fatal(err)
	}
}

func TestWriteImportStubs_Idempotent(t *testing.T) {
	dir := t.TempDir()
	cfg := &config.Config{
		ProjectRoot: dir,
		FirstYear:   2026,
		CurrentYear: 2026,
		Directories: config.Directories{Sources: "sources"},
	}
	steps := []runner.Step{
		{Output: "sources/bank/journal/2026/txns.journal", IsIngestJournal: true},
	}

	// Write once.
	if err := WriteImportStubs(cfg, steps); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(dir, "sources", "2026-imports.journal")
	info1, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}

	// Write again — mtime should not change (content unchanged).
	if err := WriteImportStubs(cfg, steps); err != nil {
		t.Fatal(err)
	}
	info2, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if info1.ModTime() != info2.ModTime() {
		t.Error("stub was rewritten despite unchanged content")
	}
}
