// Package discovery parses hledger journal files for include directives,
// resolving transitive dependencies for use in the build pipeline.
package discovery

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// hasGlob reports whether path contains any glob metacharacter.
func hasGlob(path string) bool {
	return strings.ContainsAny(path, "*?[")
}

// GetIncludes recursively parses a journal file and all files it transitively
// includes (via "include" or "!include" directives), returning their paths
// relative to baseDir.
//
// Files that are referenced but do not exist on disk are warned about and
// skipped — they may be generated by a prior build step.
// Cycles are detected and silently broken (each file appears at most once).
// The starting file itself is always the first element of the returned slice
// (unless it is missing, in which case the slice is empty).
func GetIncludes(baseDir, filePath string) ([]string, error) {
	absBase, err := filepath.Abs(baseDir)
	if err != nil {
		return nil, fmt.Errorf("resolving base dir %q: %w", baseDir, err)
	}

	absStart := toAbsPath(absBase, filePath)
	relStart, err := filepath.Rel(absBase, absStart)
	if err != nil {
		return nil, fmt.Errorf("relativising start path %q: %w", filePath, err)
	}

	visited := make(map[string]bool)
	var result []string
	if err := walk(absBase, relStart, visited, &result); err != nil {
		return nil, err
	}
	return result, nil
}

// walk does the depth-first recursive traversal, appending project-root-relative
// paths to result.
func walk(absBase, relFile string, visited map[string]bool, result *[]string) error {
	relFile = filepath.Clean(relFile)

	// Glob patterns: expand on disk and recurse into each match.
	// Missing matches are silently ignored (files may not yet be generated).
	if hasGlob(relFile) {
		absPattern := filepath.Join(absBase, relFile)
		matches, err := filepath.Glob(absPattern)
		if err != nil {
			return fmt.Errorf("glob %q: %w", absPattern, err)
		}
		for _, match := range matches {
			relMatch, err := filepath.Rel(absBase, match)
			if err != nil {
				return fmt.Errorf("resolving glob match %q: %w", match, err)
			}
			if err := walk(absBase, relMatch, visited, result); err != nil {
				return err
			}
		}
		return nil
	}

	if visited[relFile] {
		return nil // cycle or shared dep — skip
	}
	visited[relFile] = true

	absFile := filepath.Join(absBase, relFile)
	if _, err := os.Stat(absFile); os.IsNotExist(err) {
		fmt.Fprintf(os.Stderr, "warning: include file not found (may be generated): %s\n", relFile)
		return nil
	}

	*result = append(*result, relFile)

	f, err := os.Open(absFile)
	if err != nil {
		return fmt.Errorf("opening %s: %w", relFile, err)
	}
	defer func() { _ = f.Close() }()

	fileDir := filepath.Dir(absFile)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		includePath, ok := parseInclude(scanner.Text())
		if !ok {
			continue
		}

		// Resolve relative to the directory of the including file.
		absInclude := toAbsPath(fileDir, includePath)
		relInclude, err := filepath.Rel(absBase, absInclude)
		if err != nil {
			return fmt.Errorf("resolving include %q in %s: %w", includePath, relFile, err)
		}

		if err := walk(absBase, relInclude, visited, result); err != nil {
			return err
		}
	}
	return scanner.Err()
}

// parseInclude extracts the path from an "include" or "!include" directive line.
// Returns ("", false) for any other line.
func parseInclude(line string) (string, bool) {
	for _, prefix := range []string{"include ", "!include "} {
		if rest, ok := strings.CutPrefix(line, prefix); ok {
			if path := strings.TrimSpace(rest); path != "" {
				return path, true
			}
		}
	}
	return "", false
}

// toAbsPath converts path to absolute. If already absolute it is cleaned and
// returned; otherwise it is joined to base and cleaned.
func toAbsPath(base, path string) string {
	if filepath.IsAbs(path) {
		return filepath.Clean(path)
	}
	return filepath.Clean(filepath.Join(base, path))
}
